# Generated by Django 5.2.16 on 2026-07-16 04:23

import apps.core.models
import apps.crm.validators
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('entity', 'Entity')], null=True)),
                ('customer_type', models.CharField(blank=True, choices=[('donor', 'Donor'), ('bo', 'BackOffice'), ('client', 'Client')], null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_customer', to='crm.customer')),
                ('removed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=(apps.core.models.AbstractParty,),
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(blank=True, default=False, null=True)),
                ('email', models.CharField(verbose_name='Email ID')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='crm.customer')),
                ('removed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Email',
                'verbose_name_plural': 'Customer Emails',
            },
        ),
        migrations.CreateModel(
            name='CustomerEntity',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
                ('entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('removed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Entity',
                'verbose_name_plural': 'Customer Entities',
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(blank=True, default=False, null=True)),
                ('phone', models.CharField(verbose_name='Phone Number')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='crm.customer')),
                ('removed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Phone',
                'verbose_name_plural': 'Customer Phones',
            },
        ),
        migrations.CreateModel(
            name='CustomerPreferenceType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_name', models.CharField()),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String'), ('choices', 'Choices')], max_length=124)),
                ('additional_meta_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, default=dict, verbose_name='Additional Preferances Metadata (defaults, labels, is_multi_select)')),
                ('removed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.crm.validators.PreferenceTypeValidator),
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, default=dict, verbose_name='Preferances Value')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferences', to='crm.customer')),
                ('removed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('preference_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customerpreferencetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
